# Generated by Django 5.0.2 on 2024-03-04 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_article_uploaded_at_alter_article_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_main_notice',
            field=models.BooleanField(default=True),
        ),
    ]
