# Generated by Django 5.0.2 on 2024-03-07 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_article_is_main_notice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='is_main_notice',
        ),
        migrations.AddField(
            model_name='article',
            name='notice_type',
            field=models.IntegerField(choices=[('Main Notice', 1), ('Side Notice', 0)], default=True),
        ),
    ]
