# Generated by Django 5.0.2 on 2024-02-21 18:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='uploaded_at',
            field=models.DateField(auto_now_add=True, default=datetime.datetime.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
