# Generated by Django 5.0.2 on 2024-03-04 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='bill',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
