# Generated by Django 5.0.2 on 2024-03-04 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0002_event_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='bill',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
