# Generated by Django 5.0.2 on 2024-02-24 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('item_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_dept', models.CharField(max_length=50)),
                ('date_of_indent', models.DateField()),
                ('date_of_arrangement', models.DateField()),
                ('No_of_person', models.IntegerField()),
                ('payment_status', models.IntegerField(choices=[(1, 'paid'), (0, 'pending')])),
                ('menu', models.ManyToManyField(to='event_management.menuitem')),
            ],
        ),
    ]
